# Generated by Django 2.2.10 on 2020-05-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_imageset_zip_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='gender_confusion',
            field=models.BooleanField(default=False),
        ),
    ]
