version: '3'
services:
  db:
    restart: always
    image: postgres
    privileged: true
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 123456
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - /home/server/pg_data/data:/var/lib/postgresql/data/pgdata
  web:
    image: python36:djson
# your image you want to use remember to change every time
    working_dir: /code
    command: python ./imagetagger/manage.py runserver 0.0.0.0:8000
# This port needs to be the same of ports below.
    volumes:
      - .:/code
# modify django_eve to your folder name. This folder stores the code.
    ports:
      - "8000:8000"
    depends_on:
      - db
# your server port.
    restart: always



