# Generated by Django 2.2.10 on 2020-03-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0027_auto_20181114_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='L0',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='L1code',
            field=models.IntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='L1name',
            field=models.CharField(default='undefined', max_length=20),
        ),
        migrations.AddField(
            model_name='annotationtype',
            name='L2code',
            field=models.CharField(default='undefined', max_length=20, unique=True),
        ),
    ]
