# Generated by Django 2.2.10 on 2020-03-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0028_auto_20200313_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtype',
            name='L2code',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
