# Generated by Django 2.2.10 on 2020-03-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0029_auto_20200313_0145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtype',
            name='L0',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='L1name',
            field=models.CharField(default='undefined', max_length=100),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='L2code',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='annotationtype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
