# Generated by Django 2.2.10 on 2020-03-16 14:16

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0030_auto_20200313_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='vector',
            field=django_mysql.models.JSONField(default=dict, null=True),
        ),
    ]
