# Generated by Django 2.2.10 on 2020-04-15 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0031_auto_20200316_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotationtype',
            name='Color',
            field=models.CharField(default='undefined', max_length=100),
        ),
    ]
