# Generated by Django 2.2.10 on 2020-05-23 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0032_annotationtype_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportformat',
            name='include_blurred',
        ),
        migrations.RemoveField(
            model_name='exportformat',
            name='include_concealed',
        ),
    ]
