# Generated by Django 2.2.10 on 2020-05-23 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0033_auto_20200523_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportformat',
            name='include_blurred',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exportformat',
            name='include_concealed',
            field=models.BooleanField(default=True),
        ),
    ]
