# Generated by Django 2.2.10 on 2020-05-23 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotations', '0034_auto_20200523_1224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotation',
            name='_blurred',
        ),
        migrations.RemoveField(
            model_name='annotation',
            name='_concealed',
        ),
    ]
